name: fire_auth
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_modular: ^6.3.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5

  internet_connection_checker: ^1.0.0+1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  mobx_codegen: ^2.3.0
  build_runner: ^2.4.6

  mocktail: ^1.0.0

flutter:
  uses-material-design: true
